// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt8NOaU-s3F74fuzIs2ar05P990iKddvc',
    appId: '1:79691630924:web:1da727c9d4f966a88827e9',
    messagingSenderId: '79691630924',
    projectId: 'cleanarch-935ac',
    authDomain: 'cleanarch-935ac.firebaseapp.com',
    storageBucket: 'cleanarch-935ac.appspot.com',
    measurementId: 'G-W0QSY077QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyZ2_1FdWNJQQXWlkmSV_4OVzUaliUPJE',
    appId: '1:79691630924:android:04d6bb7cdf2e642c8827e9',
    messagingSenderId: '79691630924',
    projectId: 'cleanarch-935ac',
    storageBucket: 'cleanarch-935ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfVhvvYGxdYAJ7nbRYFF3XpxjHmMFq35E',
    appId: '1:79691630924:ios:fa6e86feb58d53ac8827e9',
    messagingSenderId: '79691630924',
    projectId: 'cleanarch-935ac',
    storageBucket: 'cleanarch-935ac.appspot.com',
    iosBundleId: 'com.example.zagruzkaEkrana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfVhvvYGxdYAJ7nbRYFF3XpxjHmMFq35E',
    appId: '1:79691630924:ios:fa6e86feb58d53ac8827e9',
    messagingSenderId: '79691630924',
    projectId: 'cleanarch-935ac',
    storageBucket: 'cleanarch-935ac.appspot.com',
    iosBundleId: 'com.example.zagruzkaEkrana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt8NOaU-s3F74fuzIs2ar05P990iKddvc',
    appId: '1:79691630924:web:23e292a43f1d4fa98827e9',
    messagingSenderId: '79691630924',
    projectId: 'cleanarch-935ac',
    authDomain: 'cleanarch-935ac.firebaseapp.com',
    storageBucket: 'cleanarch-935ac.appspot.com',
    measurementId: 'G-JP9FT7YQ74',
  );

}